# Generated by Django 3.0.5 on 2020-04-09 22:09

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('real_name', models.TextField()),
                ('profile', models.TextField()),
                ('url', models.TextField()),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('profile', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('format', django.contrib.postgres.fields.jsonb.JSONField()),
                ('country', models.TextField()),
                ('url', models.URLField()),
                ('artist', models.ManyToManyField(to='discogsapp.Artist')),
                ('genres', models.ManyToManyField(to='discogsapp.Genre')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discogsapp.Label')),
            ],
            options={
                'db_table': 'release',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('profile', models.TextField()),
                ('location', models.TextField()),
                ('home_page', models.TextField()),
                ('url', models.URLField()),
                ('num_wantlist', models.IntegerField()),
                ('num_lists', models.IntegerField()),
                ('rating_avg', models.FloatField()),
                ('release_contributed', models.IntegerField()),
                ('release', models.ManyToManyField(to='discogsapp.Release')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('position', models.TextField()),
                ('duration', models.FloatField()),
                ('artist', models.ManyToManyField(to='discogsapp.Artist')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discogsapp.Release')),
            ],
            options={
                'db_table': 'track',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='styles',
            field=models.ManyToManyField(to='discogsapp.Style'),
        ),
    ]
